# Codacy configuration file for file exclusions

---

exclude_paths:
  # Python cache and build files
  - "**/*.pyc"
  - "**/__pycache__/**"
  - ".venv/**"
  - "venv/**"
  - "build/**"
  - "dist/**"
  - "**.egg-info/**"
  - ".pytest_cache/**"
  - ".mypy_cache/**"
  - ".coverage"
  
  # Log files
  - "**.log"
  - ".codacy/logs/**"
  
  # Documentation and non-code files
  - "**.md"
  - "docs/**"
  - "images/**"
  
  # IDE and editor files
  - ".sonarlint/**"
  - ".vscode/**"
  - ".idea/**"
  
  # Test coverage reports
  - "htmlcov/**"
  - "coverage.xml"
  
  # Dependency lock files (usually not analyzed)
  - "uv.lock"
  
  # Sample/example directories
  - "sample_project/**"
  - "examples/**"